### ISSUE TITLE
Exemplo

### ISSUE THREAD

**Issue by gabrielgio** [HnHs/rush#1]
Esse e um exemplo de issue de descucao

**Comment by gabrielgio** [comment]
@gabrielgio Teste

**Comment by FabioReis** [comment]
Resposta de demonstassão

**Comment by gabrielgio** [comment]
@FabioReis Reply

**Comment by FabioReis** [comment]
@FabioReis teste

**Comment by midori-fukami** [comment]
@FabioReis Demosntração*******
